---
name: Install runtime dependencies
description: Install the runtime dependencies for CompilerGym.
runs:
    using: composite
    steps:
        - name: Install runtime dependencies
          run: |
              if [ "$(uname)" = "Darwin" ]; then
                  brew install zlib
              else
                  sudo apt-get install libtinfo5
              fi
              python -m pip install -U pip wheel
          shell: bash
