---
name: Install runtime dependencies
description: Install the runtime dependencies for CompilerGym.
runs:
    using: composite
    steps:
        - name: Install runtime dependencies
          run: |
              if [ "$(uname)" = "Darwin" ]; then
                  brew install zlib
              fi
          shell: bash

        # DGL creates ~/.dgl on first run and I have found that this will fail
        # if run from pytest / bazel. Suppress errors if DGL is not installed.
        - name: Initialize DGL
          run: |
              python -c 'import dgl; print(dgl.__version__)' || true
          shell: bash
