---
name: Install runtime dependencies
description: Install the runtime dependencies for CompilerGym.
runs:
    using: composite
    steps:
        - uses: ./.github/actions/install-runtime-dependencies

        - name: Install MLIR env runtime dependencies
          run: |
              if [ "$(uname)" = "Darwin" ]; then
                  # TODO(boian): figure out how to install the C++ std library.
                  echo "Error: Darwin is not supported"
                  exit 1
              else
                 sudo apt-get install libstdc++-9-dev
              fi
          shell: bash
