---
name: CI

on:
    push:
        branches:
            - development
            - stable
    pull_request:
    schedule:
        - cron: 0 0 * * 0 # weekly

jobs:
    linux_build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-python@v2
              with:
                  python-version: 3.9

            - uses: ./.github/actions/install-build-dependencies

            - name: Build Python wheel
              run: make bdist_wheel bdist_wheel-linux-rename
              env:
                  CC: clang
                  CXX: clang++
                  BAZEL_OPTS: --batch
                  BAZEL_FETCH_OPTS: --config=ci
                  BAZEL_BUILD_OPTS: --config=ci

            - name: Upload Python wheel
              uses: actions/upload-artifact@v2
              with:
                  name: manylinux-wheel
                  path: dist/*.whl
                  if-no-files-found: error
                  retention-days: 7

    macos_build:
        runs-on: macos-latest

        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-python@v2
              with:
                  python-version: 3.9

            - uses: ./.github/actions/install-build-dependencies

            - name: Build Python wheel
              run: make bdist_wheel
              env:
                  BAZEL_OPTS: --batch
                  BAZEL_FETCH_OPTS: --config=ci
                  BAZEL_BUILD_OPTS: --config=ci

            - name: Upload Python wheel
              uses: actions/upload-artifact@v2
              with:
                  name: macos-wheel
                  path: dist/*.whl
                  if-no-files-found: error
                  retention-days: 7

    linux_test:
        needs: linux_build
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                python: [3.6, 3.7, 3.8, 3.9]

        steps:
            - uses: actions/checkout@v2

            - name: Download Python wheel
              uses: actions/download-artifact@v2
              with:
                  name: manylinux-wheel

            - name: Install wheel
              run: python -m pip install *.whl

            - uses: ./.github/actions/install-runtime-dependencies

            - uses: ./.github/actions/install-test-dependencies

            - name: Run the test suite
              run: make install-test

    macos_test:
        needs: macos_build
        runs-on: macos-latest

        strategy:
            fail-fast: false
            matrix:
                python: [3.8, 3.9]

        steps:
            - uses: actions/checkout@v2

            - name: Download Python wheel
              uses: actions/download-artifact@v2
              with:
                  name: macos-wheel

            - name: Install wheel
              run: python -m pip install *.whl

            - uses: ./.github/actions/install-runtime-dependencies

            - uses: ./.github/actions/install-test-dependencies

            - name: Run the test suite
              run: make install-test

    pytest-cov:
        needs: linux_build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Download Python wheel
              uses: actions/download-artifact@v2
              with:
                  name: manylinux-wheel

            - name: Install wheel
              run: python -m pip install *.whl

            - uses: ./.github/actions/install-runtime-dependencies

            - uses: ./.github/actions/install-test-dependencies

            - name: Run the test suite with coverage
              # Note the `|| true` as we don't care about failing tests in this
              # job.
              run: make install-test-cov || true
              env:
                  CC: clang
                  CXX: clang++

            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v1
              with:
                  files: ./coverage.xml
              if: ${{ always() }}
